const FRIDGE_ITEM_LIST_SCREEN = "FridgeItemList";
const SHOW_FRIDGE_ITEM_DETAIL_SCREEN = "ShowFridgeItemDetail";
const ADD_FOOD_ITEM_BY_FORM_SCREEN = "AddFoddItemByForm";
const HOME_SCREEN = "Home";
const FRIDGE_ACTION_NAVIGATION = "Fridge";
const RECIPES_ACTION_NAVIGATION = "Recipes";
const PROFILE_SCREEN = "Profile";
const SIGNIN_SCREEN = "SignIn";
const SIGNUP_SCREEN = "SignUp";
const AUTHENTICATION_NAVIGATION = "Auth";
const MAIN_BOTTOM_TAB_NAVIGATION = "Main";
const CAMERA_SCREEN = "Camera";
const ADD_BY_FORM_NAVIGATION = "AddByFormNavigation";
const RECIPE_LIST_SCREEN = "RecipeListScreen";
const RECIPE_DETAILS_SCREEN = "RecipeDetailScreen";

export {
    FRIDGE_ITEM_LIST_SCREEN,
    SHOW_FRIDGE_ITEM_DETAIL_SCREEN,
    ADD_FOOD_ITEM_BY_FORM_SCREEN,
    HOME_SCREEN,
    FRIDGE_ACTION_NAVIGATION,
    RECIPES_ACTION_NAVIGATION,
    PROFILE_SCREEN,
    SIGNIN_SCREEN,
    SIGNUP_SCREEN,
    AUTHENTICATION_NAVIGATION,
    MAIN_BOTTOM_TAB_NAVIGATION,
    CAMERA_SCREEN,
    ADD_BY_FORM_NAVIGATION,
    RECIPE_LIST_SCREEN,
    RECIPE_DETAILS_SCREEN
}